### ISSUE TITLE
crash when clicking on "Aggregate" operation

### ISSUE THREAD

**Issue by rejoc** [Studio3T/robomongo#1600]
studio-3T 2018.5.1 on linux
crash as soon as I hit the "Aggregate" button

any idea ?
```
studio3t/Studio-3T
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /tmp/3T-998618019323640113/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
com.install4j.api.launcher.SplashScreen$ConnectionException: no splash screen available
 at com.install4j.api.launcher.SplashScreen.hide(SplashScreen.java:43)
 at com.install4j.runtime.launcher.integration.gui.WindowChecker$1.run(WindowChecker.java:16)
 at com.install4j.runtime.launcher.integration.gui.WindowChecker.run(WindowChecker.java:60)
...
java: /build/buildd/gtk2-engines-oxygen-1.4.5/src/animations/oxygencomboboxdata.cpp :87 : void Oxygen::ComboBoxData::setButton(GtkWidget*):  l'assertion « !_button._widget » a échoué.
Abandon (core dumped)

```

**Comment by xGanimeDx** [comment]
@rejoc Your issue related to "Studio 3T" application or to "Robo 3T"? If answer is "Studio 3T" better ask your question here https://studio3t.com/feedback/

**Comment by simsekgokhan** [comment]
Seems like this problem is related to "Studio 3T" application not "Robo 3T, closing.
